ALTER TABLE operations
ADD COLUMN numero_escale VARCHAR(50) NULL,
ADD COLUMN nom_navire VARCHAR(150) NULL,
ADD COLUMN poste_quai VARCHAR(100) NULL,
ADD COLUMN type_operation ENUM('CHARGEMENT', 'DECHARGEMENT', 'MANUTENTION') NOT NULL DEFAULT 'MANUTENTION';
